# Generated by Django 2.2.24 on 2021-08-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layover_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_rating',
        ),
        migrations.AlterField(
            model_name='place',
            name='place_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layover_app.Subcategory'),
        ),
    ]
