# Generated by Django 2.2.24 on 2021-06-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layover_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='destination_icao',
        ),
    ]
