# Generated by Django 2.2.24 on 2021-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layover_app', '0002_auto_20210801_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_google_id',
            field=models.CharField(max_length=200),
        ),
    ]
