# Generated by Django 2.2.24 on 2021-09-05 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layover_app', '0005_destination_destination_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_text', models.CharField(max_length=1000)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('comment_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layover_app.Place')),
            ],
        ),
    ]
