# Generated by Django 2.2.24 on 2021-09-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layover_app', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_lat',
            field=models.DecimalField(decimal_places=10, default=50.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='place',
            name='place_long',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
    ]
