# Generated by Django 2.2.24 on 2021-09-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layover_app', '0008_auto_20210921_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
