# Generated by Django 2.2.24 on 2021-09-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layover_app', '0009_auto_20210927_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_google_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_googlemaps',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_image_url',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=50.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_lng',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
